### ISSUE TITLE
Issue: KANBAN BOARD

### ISSUE THREAD

**Issue by Ntwali-Josue** [Ntwali-Josue/kanban-board#21]
[Kanban project](https://github.com/Ntwali-Josue/kanban-board/projects/1)
**In our team, we are 2 people**

- Student A as KARANGWA Ntwali Josue
- Student B as Angel Diaz

**Comment by henatan99** [comment]
Hi @Ntwali-Josue, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] There should be a circle with the user's avatar on each card. See the example below:
![image](https://user-images.githubusercontent.com/64894927/132259272-323ef000-f946-45f0-9999-faf17ed96311.png)
- [ ] Don't use 'Student A', 'Student B' prefixes for Group tasks.  Keep the prefix as 'group task' for all group tasks. :pray: 
![image](https://user-images.githubusercontent.com/64894927/132259334-dfc8b3aa-830c-43ba-ab1c-a1ee9c729065.png)
![image](https://user-images.githubusercontent.com/64894927/132259379-366b2cc6-5d1e-46e0-8961-a8dbe25cb07f.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ad9311** [comment]
We made the required changes and now all tasks show the avatar of their assignee and group tasks have reedited back. 👍🏽

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @Ntwali-Josue &  @ad9311,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
